<Project Sdk="MSTest.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.10" />
    </ItemGroup>

</Project>
